import { db } from "../lib/db";

/**
 * Derives a AES-256-GCM CryptoKey from a passphrase + salt using PBKDF2.
 * IMPORTANT: Salt must be randomly generated by the sender and transmitted
 * as the very first unencrypted message over the WebRTC data channel.
 * Both peers MUST use the same salt to derive the same key.
 */
export async function deriveKey(passphrase: string, salt: Uint8Array): Promise<CryptoKey> {
    const encoder = new TextEncoder();
    const encodedPhrase = encoder.encode(passphrase);

    const baseKey = await window.crypto.subtle.importKey(
        "raw",
        encodedPhrase,
        "PBKDF2",
        false,
        ["deriveKey"]
    );

    return await window.crypto.subtle.deriveKey(
        {
            name: "PBKDF2",
            salt: salt as Uint8Array<ArrayBuffer>,
            iterations: 100000,
            hash: "SHA-256"
        },
        baseKey,
        {
            name: "AES-GCM",
            length: 256
        },
        false,
        ["encrypt", "decrypt"]
    );
}

/**
 * Encrypts a single ArrayBuffer chunk using AES-GCM.
 * Prepends the random 12-byte IV to the encrypted output so it can be
 * extracted during decryption.
 */
export async function encryptChunk(chunk: ArrayBuffer, key: CryptoKey): Promise<ArrayBuffer> {
    const iv = window.crypto.getRandomValues(new Uint8Array(12));
    const encryptBuffer = await window.crypto.subtle.encrypt(
        { name: 'AES-GCM', iv },
        key,
        chunk
    );

    // Layout: [12 bytes IV][encrypted payload]
    const combined = new Uint8Array(iv.byteLength + encryptBuffer.byteLength);
    combined.set(iv, 0);
    combined.set(new Uint8Array(encryptBuffer), iv.byteLength);
    return combined.buffer;
}

/**
 * Decrypts a chunk that was encrypted by encryptChunk().
 * Extracts the 12-byte IV from the front, then decrypts the remainder.
 */
export async function decryptChunk(combinedChunk: ArrayBuffer, key: CryptoKey): Promise<ArrayBuffer> {
    const view = new Uint8Array(combinedChunk);
    const iv = view.slice(0, 12);
    const encryptedData = view.slice(12);

    return await window.crypto.subtle.decrypt(
        { name: 'AES-GCM', iv },
        key,
        encryptedData
    );
}

/**
 * Streams decrypted chunks into a Blob URL for download.
 * Records must be pre-sorted by chunkIndex before calling.
 */
export async function compileChunksToUrl(
    records: { chunkIndex: number; data: ArrayBuffer }[],
    mimeType: string,
    key: CryptoKey
): Promise<string> {
    const stream = new ReadableStream({
        async start(controller) {
            try {
                for (const record of records) {
                    const decrypted = await decryptChunk(record.data, key);
                    controller.enqueue(new Uint8Array(decrypted));
                }
                controller.close();
            } catch (error) {
                controller.error(new Error("Decryption or stream failure: " + error));
            }
        }
    });

    const response = new Response(stream, { headers: { "Content-Type": mimeType } });
    const blob = await response.blob();
    return URL.createObjectURL(blob);
}