/**
 * crypto.ts
 *
 * AES-GCM-256 key derivation, single-chunk encrypt/decrypt, and Blob URL assembly.
 *
 * Key design decisions
 * ────────────────────
 * extractable: true
 *   CryptoKey objects cannot cross Web Worker thread boundaries — only their
 *   serialised JWK representation can.  Setting extractable:true allows
 *   crypto.subtle.exportKey('jwk', key) so chunker.ts and useWebRTC.ts can
 *   hand the key to cryptoWorker.js for parallel off-thread crypto operations.
 *
 *   Security trade-off: JS code in this origin can call exportKey() and read
 *   the raw key bytes.  For a browser-only P2P tool with no server component
 *   this is acceptable — the key is derived fresh each session and never
 *   leaves the tab.
 *
 * salt typing
 *   PBKDF2 requires the salt to be a BufferSource.  We accept Uint8Array and
 *   cast to Uint8Array<ArrayBuffer> which satisfies TypeScript's strict DOM
 *   lib overload (it rejects Uint8Array<ArrayBufferLike> because that union
 *   includes SharedArrayBuffer, which the Web Crypto API does not accept).
 *
 * Window vs globalThis
 *   Worker threads do not have a `window` object; they expose crypto directly
 *   on `globalThis` (or just as the global `crypto`).  Using `crypto.subtle`
 *   (without the `window.` prefix) works in both the main thread and workers,
 *   so every call here uses the unprefixed form.
 */

// ── Key derivation ─────────────────────────────────────────────────────────────

/**
 * Derive an AES-GCM-256 CryptoKey from a passphrase and salt using PBKDF2.
 *
 * @param passphrase  - user-supplied secret string
 * @param salt        - 16-byte random value generated by the sender and
 *                      transmitted as the first message on the data channel
 *                      so both peers derive the identical key
 */
export async function deriveKey(passphrase: string, salt: Uint8Array): Promise<CryptoKey> {
    const baseKey = await crypto.subtle.importKey(
        'raw',
        new TextEncoder().encode(passphrase),
        'PBKDF2',
        false,          // base key does not need to be extractable
        ['deriveKey']
    );

    return crypto.subtle.deriveKey(
        {
            name:       'PBKDF2',
            salt:       salt as Uint8Array<ArrayBuffer>,
            iterations: 100_000,
            hash:       'SHA-256',
        },
        baseKey,
        { name: 'AES-GCM', length: 256 },
        true,           // extractable = true so chunker + useWebRTC can export JWK for workers
        ['encrypt', 'decrypt']
    );
}

// ── Single-chunk helpers ───────────────────────────────────────────────────────
// Used by the sequential fallback path in chunker.ts when the key cannot be
// exported (should not happen with extractable:true, but kept as a safety net).

/**
 * Encrypt one ArrayBuffer chunk with AES-GCM.
 *
 * Output layout (16 KB input → ~16 KiB + 28 bytes output):
 *   [0..11]   random 12-byte IV
 *   [12..]    AES-GCM ciphertext  +  16-byte authentication tag
 *
 * The IV is prepended so decryptChunk() can extract it without any out-of-band
 * communication.
 */
export async function encryptChunk(chunk: ArrayBuffer, key: CryptoKey): Promise<ArrayBuffer> {
    const iv = crypto.getRandomValues(new Uint8Array(12));

    const ciphertext = await crypto.subtle.encrypt(
        { name: 'AES-GCM', iv },
        key,
        chunk
    );

    const combined = new Uint8Array(iv.byteLength + ciphertext.byteLength);
    combined.set(iv, 0);
    combined.set(new Uint8Array(ciphertext), iv.byteLength);
    return combined.buffer;
}

/**
 * Decrypt a chunk produced by encryptChunk().
 *
 * Extracts the first 12 bytes as the IV, then decrypts the remainder.
 * Both iv and encryptedData are copied via ArrayBuffer.slice() so the result
 * is backed by a plain ArrayBuffer (not SharedArrayBuffer), satisfying
 * crypto.subtle's strict TypeScript overload.
 */
export async function decryptChunk(combinedChunk: ArrayBuffer, key: CryptoKey): Promise<ArrayBuffer> {
    const iv            = new Uint8Array(combinedChunk.slice(0, 12));
    const encryptedData = new Uint8Array(combinedChunk.slice(12));

    return crypto.subtle.decrypt(
        { name: 'AES-GCM', iv },
        key,
        encryptedData
    );
}

// ── Blob URL assembly (RAM fallback) ──────────────────────────────────────────

/**
 * Decrypt an ordered array of chunk records and assemble them into a Blob URL
 * suitable for a download link.
 *
 * This is only used on browsers that do not support showSaveFilePicker()
 * (Firefox, older Safari).  On Chrome/Edge, useWebRTC.ts writes directly to
 * disk via FileSystemWritableFileStream, which has no memory limit.
 *
 * Records must be sorted by chunkIndex before calling — the function streams
 * them in the order given.
 */
export async function compileChunksToUrl(
    records:  { chunkIndex: number; data: ArrayBuffer }[],
    mimeType: string,
    key:      CryptoKey
): Promise<string> {
    const stream = new ReadableStream<Uint8Array>({
        async start(controller) {
            try {
                for (const record of records) {
                    const plain = await decryptChunk(record.data, key);
                    controller.enqueue(new Uint8Array(plain));
                }
                controller.close();
            } catch (err) {
                controller.error(new Error('Decryption or stream failure: ' + err));
            }
        },
    });

    const response = new Response(stream, { headers: { 'Content-Type': mimeType } });
    const blob     = await response.blob();
    return URL.createObjectURL(blob);
}